// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackArrowButton: typeof import('./../components/buttons/BackArrowButton.vue')['default']
    ConfirmButton: typeof import('./../components/buttons/ConfirmButton.vue')['default']
    CountryStore: typeof import('./../components/CountryStore.vue')['default']
    DeleteButton: typeof import('./../components/buttons/DeleteButton.vue')['default']
    EditButton: typeof import('./../components/buttons/EditButton.vue')['default']
    Loader: typeof import('./../components/Loader.vue')['default']
    Logo: typeof import('./../components/Logo.vue')['default']
    Navigation: typeof import('./../components/Navigation.vue')['default']
    PageHeading: typeof import('./../components/PageHeading.vue')['default']
    RouterButton: typeof import('./../components/buttons/RouterButton.vue')['default']
    Topbar: typeof import('./../components/Topbar.vue')['default']
    VuelidateError: typeof import('./../components/VuelidateError.vue')['default']
  }
}

export { }
